//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/08/31 - 01:19:44
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System.Text;
using System.Runtime.Serialization;
using System.Collections.Generic;
using System;

namespace CroweHorwathAssignment.Data.Models.DTO
{
    [DataContract()]
    public partial class tblTagDTO
    {
        [DataMember()]
        public int tagId { get; set; }

        [DataMember()]
        public string tagName { get; set; }

        [DataMember()]
        public string tagDescription { get; set; }

        public tblTagDTO()
        {
        }

        public tblTagDTO(int tagId, string tagName, string tagDescription)
        {
			this.tagId = tagId;
			this.tagName = tagName;
			this.tagDescription = tagDescription;
        }
    }
}